### ISSUE TITLE
File "/home/administrator/BlenderPhong/phong.blend/phong.py", line 79, in main FileNotFoundError: [Errno 2] No such file or directory: '/home/weitang114/Dev/blenderSC/missed_stls.txt'

### ISSUE THREAD

**Issue by xidianxiaofeixian** [WeiTang114/BlenderPhong#4]
Trouble telling how to solve this problem? Thank you

**Comment by AymanMukh** [comment]
In phong.py Replace:     

    do_model(model, image_dir) 

which is found in def main()   by

    with open(models_list) as f:
        models = f.read().splitlines()

    for model in models:
        do_model(model, image_dir)

also replace 

    models= argv[0]
with 

    models_list = argv[0]

and then run command for Multiple models directly by:
blender phong.blend --background --python phong.py -- models.txt  ./tmp

**Comment by xidianxiaofeixian** [comment]
NameError: name 'models_list' is not defined

**Comment by WeiTang114** [comment]
This issue should be fixed by this commit https://github.com/WeiTang114/BlenderPhong/commit/39688979b26a30e8a891412c833faaf9051685dc
There was some unused old code in the blender file. I rebuild phong.blend which should be fine.
So I'm closing this issue. Feel free to open it if there is still any problem.
